services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-centrorum}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-devpassword}
      POSTGRES_DB: ${POSTGRES_DB:-centrorum}
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
  backend:
    build: ./backend
    command: bash -lc "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/app
    environment:
      DATABASE_URL: postgresql://centrorum:devpassword@db:5432/centrorum
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY:-changeme}
      DEBUG: "1"
      ALLOWED_HOSTS: "*"
      CORS_ALLOWED_ORIGINS: "http://localhost:5173"
    depends_on: [db]
    ports:
      - "8000:8000"
  frontend:
    build: ./frontend
    command: npm run dev -- --host
    volumes:
      - ./frontend:/app
    environment:
      VITE_API_URL: http://localhost:8000/api
      ROLLUP_SKIP_NODE_NATIVE: "1"
    ports:
      - "5173:5173"
    depends_on: [backend]
volumes:
  dbdata:
