# Generated by Django 5.1.1 on 2025-10-27 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='type',
            field=models.CharField(choices=[('event', 'Event'), ('tutor', 'Tutoring'), ('job', 'Job'), ('resource', 'Resource'), ('post', 'Post')], max_length=16),
        ),
    ]
