# Generated by Django 5.1.1 on 2025-10-27 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_alter_listing_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rsvp',
            name='status',
            field=models.CharField(choices=[('going', 'Going'), ('interested', 'Interested'), ('not_going', 'Not Going')], default='going', max_length=16),
        ),
    ]
